version: "3.4"

services:
  app:
    image: cypress-ui-test
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /e2e
    volumes:
      - ./:/e2e
